import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import "./globals.css";
import ThemeProvider from "@/providers/ThemeProvider";
import Sidebar from "@/components/sidebar/Sidebar";
import { Container } from "@mui/material";
import Footer from '@/components/common/Footer';


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body >
        <ThemeProvider>
          <div style={{ display: 'flex' }}>
            {/* <Sidebar /> */}
            <Container sx={{pb:"7rem",pt:"1rem"}}>
              {children}
              <Footer />
            </Container>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}